---
- name: Install Magerun
  get_url:
    url: "{{ magerun_phar_url }}"
    dest: "{{ magerun_bin_path }}"
    force: true
    mode: 0755

- name: Retrieve Magerun tab completions
  command: curl -4Ls {{ magerun_completion_url }} -o /tmp/magerun-completion-{{ magerun_version }}.bash
  args:
    creates: /tmp/magerun-completion-{{ magerun_version }}.bash
    warn: false

- name: Install Magerun tab completions
  command: rsync -c --chmod=0644 --info=name /tmp/magerun-completion-{{ magerun_version }}.bash {{ magerun_completion_path }}
  args:
    warn: false
  register: magerun_completion
  changed_when: magerun_completion.stdout == "magerun-completion-{{ magerun_version }}.bash"
