---
- include: database.yml
  tags: magento-setup-database
- include: self-signed-certificate.yml
  tags: magento-setup-self-signed-certificate

- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ magento_sites }}"

- name: Create logs folder of sites
  file:
    path: "{{ www_root }}/{{ item.key }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ magento_sites }}"

- name: Create Magento php-fpm configuration file
  template:
    src: php-fpm.conf.j2
    dest: /etc/php/7.0/fpm/pool.d/magento.conf
  notify: reload php-fpm

- name: Disable default PHP-FPM pool
  command: mv /etc/php/7.0/fpm/pool.d/www.conf /etc/php/7.0/fpm/pool.d/www.disabled
  args:
    creates: /etc/php/7.0/fpm/pool.d/www.disabled
  when: disable_default_pool | default(true)
  notify: reload php-fpm

- include: nginx.yml
  tags: wordpress-setup-nginx

- name: Setup Magento system cron
  cron:
    name: "{{ item.key }} Magento cron"
    minute: "*/5"
    user: "{{ web_user }}"
    job: "cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }} && sh cron.sh > /dev/null 2>&1"
    cron_file: "magento-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ magento_sites }}"
  when: site_env.disable_mage_cron and not item.value.multisite.enabled | default(false)
